version: '2'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      - cluster.name=percolator-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data

  app:
    image: eaudeweb/percolator
    env_file:
      - ./docker/percolator.env
    volumes:
      - static-files:/var/local/percolator/static
    depends_on:
      - elasticsearch

  nginx:
    image: nginx:latest
    environment:
      NGINX_CONF: |-
        upstream app {
          ip_hash;
          server app:5000;
        }

        server {
          listen 80;

          access_log /var/log/nginx/access.log main;
          location / {
            proxy_pass http://app/;
          }
          location /static {
            sendfile on;
            tcp_nopush on;
            gzip on;
            gzip_types text/plain application/x-javascript text/css;
            expires 1d;
            root /var/local/percolator;
          }
        }
    command: /bin/sh -c 'echo "$$NGINX_CONF" > /etc/nginx/conf.d/default.conf && exec nginx -g "daemon off;"'
    volumes:
      - static-files:/var/local/percolator/static:ro
    depends_on:
      - app

volumes:
  esdata:
    driver: local
  static-files:
    driver: local
